### ISSUE TITLE
Partial Refunds don't sync over to Civi

### ISSUE THREAD

**Issue by josephlacey** [twomice/com.joineryhq.eventbrite#9] opened 2019-06-12 20:17 UTC
EventBrite allows partial refunds, in cases where folks might overpay or don't get group discounts.  These don't update their correlative Civi record.

**Comment by twomice** [comment] 2019-06-18 15:14
Hi @josephlacey I'm having trouble reproducing this one on my testing setup. E.g., see attached image, which reflects a $1.00 refund on a $2.70 order:
![partial_refund_order_959644437](https://user-images.githubusercontent.com/759449/59696389-81892b00-91b1-11e9-96a2-10ee631caafd.png)

Can you point me to the order ID on your EB system, for the order that's not properly syncing the refund?

**Comment by josephlacey** [comment] 2019-06-18 15:23
Interesting.  Order# 963617652 should be partially refunded.

**Comment by twomice** [comment] 2019-06-18 18:01
Hi @josephlacey This bad behavior appears actually to be brought out by an edge case when the un-refunded total is small enough that Eventbrite fees go down to zero -- in certain case with very small ticket prices like $2. In any case, the situation did highlight legitimate bugs, and I've made commits to fix those. 

So, testing on this fix should use those same small ticket prices.

I'm not able to test immediately on my EB account, due to policies of my payment processor, which require waiting 3-4 business days until payment is resolved, before making a partial refund. Are you able to test this latest code with your EB setup?

**Comment by josephlacey** [comment] 2019-06-18 18:48
> Hi @josephlacey This bad behavior appears actually to be brought out by an edge case when the un-refunded total is small enough that Eventbrite fees go down to zero -- in certain case with very small ticket prices like $2. In any case, the situation did highlight legitimate bugs, and I've made commits to fix those.

Ha, why am I not surprised?

> So, testing on this fix should use those same small ticket prices.
> 
> I'm not able to test immediately on my EB account, due to policies of my payment processor, which require waiting 3-4 business days until payment is resolved, before making a partial refund. Are you able to test this latest code with your EB setup?

Sure, I can test this.  I would say this isn't a launch blocker.

**Comment by twomice** [comment] 2019-07-02 17:53
Fixed in 54e87d5

**Closed as completed by twomice** 2019-07-02 17:53 UTC
