### ISSUE TITLE
The requested page could not be found.

### ISSUE THREAD

**Issue by nloui** [twomice/com.joineryhq.eventbrite#25] opened 2021-01-02 06:38 UTC
When you go to /civicrm/admin/eventbrite/settings

It just says: "The requested page could not be found."

/civicrm/admin/eventbrite
works but the table shows:

$link.title  | Settings | Eventbrite API key; debug settings.
-- | -- | --
$link.title  | Events | Configurations for specific events.

Running CiviCRM 5.32.2

**Comment by twomice** [comment] 2021-03-08 17:26
Hi @nloui I'm not seeing exactly what you see; under Drupal 7, CiviCRM 5.32.2, I get this:

![settings](https://user-images.githubusercontent.com/759449/110356743-2db31b00-8000-11eb-8634-e0788b3b1991.png)

I'm not sure why the buttons are not displaying -- I've created a separate issue for that: #26  I've also created a separate issue for this missing icons you describe on the main page at /civicrm/admin/eventbrite: #27 

As for the current issue, "requested page could not be found", I wonder if there's some caching issue at fault here. Could you try clearing CiviCRM cache or rebuilding menus to see if that will make the page available again?

**Comment by twomice** [comment] 2021-03-09 16:08
Tagged as Invalid, pending more information from OP to help reproduce the issue.

**Comment by twomice** [comment] 2022-10-20 15:46
I'm including this issue in a batch closing of older tickets. It may be that this this issue has been resolved, or we may need more information. Please feel free to re-open.

Also note: FYI, I've updated the README file with a note on project status. Because we don't use EB here, it's hard for me to keep this up to date, though I'm hopeful some EB user organization will be interested in sponsoring the work to get it working agian.

## NOTICE of project status
### This project is known to have significant issues with the current EventBrite API.
Although it worked well when first released, EB has made changes to their API, and this extension is very likely not to work completely, or perhaps in any usable way.

If you're a current EventBrite user who'd like to help sponsor the work needed get this working again, please contact us directly via https://joineryhq.com/ to discuss your needs.

**Closed as completed by twomice** 2022-10-20 15:46 UTC
Labels: invalid
