### ISSUE TITLE
Not receiving any data from Eventbrite

### ISSUE THREAD

**Issue by yosefromano** [twomice/com.joineryhq.eventbrite#11] opened 2019-07-04 05:16 UTC
I set up the integration. Everything looks good but I am not receiving any data from Eventbrite. 
The scheduled job logs do not show any errors.

**Comment by twomice** [comment] 2019-07-05 20:09
Hi @yosefromano. Thanks for reporting this. To help debug your situation, please double-check the following:

1. Visit Administer > CiviEvent > Eventbrite Integration > Settings. Upon opening the page, you should see the message, "Eventbrite webhooks have been successfully configured in your Evenbrite account." This confirms that the extension has been able to set up webhooks properly in your Eventbrite account. If not, you will see an error message, "Error establishing webhook configuration via Eventbrite API. Eventbrite said: ..." with an explanation of the Eventbrite error.

2. Are you running this extension on a website that is accesible from the Internet? For example, a development server on your local machine will probably not be accessible from the Internet. As such, Eventbrite webhooks will not be able to contact your site with the latest information, and therefore no syncronization will happen.

3. Log into Evenbrite and then visit https://www.eventbrite.com/account-settings/webhooks . There should be two webhooks there, pointing to your site:  Action "order.updated" pointing to Payload URI "https://[yoursite.com]/civicrm/eventbrite/webhook", and Action "attendee.updated", also pointing to the same Payload URI. If these don't exist, you should see some message about it in item number 1 above.

4. Has Eventbrite fired the correct webhook for your data? For example, when you place a ticket order, Eventbrite should be firing both webhooks, "order.updated" and "attendee.updated". For each webhook, you can see the events that were fired (at https://www.eventbrite.com/account-settings/webhooks) by clicking the "Details" button and examining the list of "Recent Requests".  It's very unlikely that Eventbrite failed to fire the webhook, but in case that does happen, this would be an issue for Eventbrite support.

5. Did your CiviCRM site receive the webhook notification? All Eventbrite webhook notifications are stored in a queue for processing later by the appropriate Scheduled Job (see below). This queue is stored in the database table civicrm_eventbrite_queue. You can examine the contents of that table directly through SQL, or you can use the CiviCRM API explorer ([yoursite.com]/civicrm/api) to run the EventbriteQueue.get operation and thereby retrieve a list of all queue entries. If Eventbrite sent the webhook notification (see item 4 above), but the webhook notification is not contained in the queue, this will prevent data syncronization. Please let me know if that's the case.

6. What is the output of the "Call Eventbrite.Runqueue API" scheduled job? This job is, by default, configured to run "Always", i.e., each time CiviCRM Scheduled Jobs are run. The log output of this Scheduled Job may indicate some errors. Please navigate to Administer > System Settings > Scheduled Jobs, locate the "Call Eventbrite.Runqueue API" job, and click "View Job Log" for this job. In the job log, locate the most recent entry beginning with "Finished execution of Call Eventbrite.Runqueue API", and examine the result displayed for that run. The result is a serialized array of information which may be hard to decipher. Please copy/paste that text here if you'd like help understanding it.

Thank you.

**Comment by twomice** [comment] 2019-07-05 20:10
Also fyi, @yosefromano A new version 1.2 was released today with bug fixes (not related to this issue). You may want to upgrade to the latest code when you have a chance.

**Comment by agileware-pengyi** [comment] 2019-07-17 07:25
Hi, we have the same problem with our client. In our case, it is because `CRM_Utils_System::url` generate a wrong WordPress URL to the Eventbrite webhook. So, manually fix the URL in the Eventbrite website will solve it. We can submit our fix as PR if needed.

CIVICRM-1278

**Comment by twomice** [comment] 2019-07-17 13:11
@agileware-pengyi Yes, PR is definitely welcome here.

@yosefromano Are you on WordPress? If so, this might be a good explanation.

**Comment by agileware-pengyi** [comment] 2019-07-18 05:03
#13 may fix this.

**Comment by yosefromano** [comment] 2019-09-26 21:17
@twomice Sorry for being MIA. Got very busy all of a sudden. I just came back to this and realized that it works perfectly fine. I initially thought that once set up it would also be able to sync past participants. Is it?
As for new participants, these sync properly into CiviCRM. 
I am on D7

**Comment by twomice** [comment] 2019-09-26 22:22
Hi @yosefromano Glad to hear it's working as designed. You raise a good question here:

>  initially thought that once set up it would also be able to sync past participants. Is it?

The sync happens in near-real-time based on EB webhooks, so EB tickets will only be synced into CiviCRM if they are purchased (or modified) after you set up the appropriate configuration for event and ticket types within this extension.

There is discussion in #14 about modifications that would allow syncing of tickets, if the event start date is no more than 30 days in the past. You may want to join that discussion if that's something you're interested in.

For now, I will close this ticket and mark it "As designed". Feel free to re-open if you think that's not the case.

Thanks again for filing the ticket and communicating with us about it!

**Closed as completed** 2019-09-26 22:22 UTC
Labels: As designed
